### ISSUE TITLE
Not able to send events using React Native SDK

### ISSUE THREAD

**Issue by basit-rayn** [rudderlabs/rudder-sdk-react-native#311]
We are using an open-source Rudderstack dataPlane, and also open-source controlPlane(source configuration hosting) which we have self-hosted. We have initialized the react native SDK of Rudderstack but we are not able to fire events successfully. The connection is getting successfully established with controlPlane but still, the events are not getting fired due to some unknown reasons.

The events are getting fired successfully from your server and web-based SDKs but for mobile SDKs, it is not working fine.

This is the payload, the same that is mentioned on RudderStack's official documentation as well
```json
      {
        email: "testuser@example.com",
        location: "UK",
      }
```

**Here is the example** code that I have added in my App

``` javascript
  // React Native code snippet
  console.log('Setting up rudderstack');
  const WRITE_KEY = '';
  const DATA_PLANE_URL = '';
  const CONTROL_PLANE_URL = '';
  const rudderInitialise = async () => {
    await rudderClient.setup(WRITE_KEY, {
      dataPlaneUrl: DATA_PLANE_URL,
      controlPlaneUrl: CONTROL_PLANE_URL,
    });
    rudderClient.identify(
      "test_userId",
      {
        email: "testuser@example.com",
        location: "UK",
      },
      null
    )
  };
  rudderInitialise().catch(console.error);
```

 **We are facing this issue on all devices and OS.**

 Here is the **error stack trace** from React Native side

``` console
 LOG  RudderSDK: Debug: Initializing Rudder RN SDK version: 1.11.3
 LOG  RudderSDK: Debug: setup: created config
 LOG  no languages returned
 LOG  RudderSDK: Debug: setup: setup completed
 LOG  SDK is initalised
```

These are the logs from our source configuration

`INFO:     10.0.49.113:43420 - "GET /react_native/write_key/sourceConfig?p=android&v=1.21.2&bv=33 HTTP/1.1" 200 OK`

There are no logs in dataPlane despite increasing its verbosity.

The error occurring on:

- [ ] Android

**Steps to reproduce the Behaviour:**

1. Initialise React-Native SDK
```javascript
const rudderInitialise = async () => {
    await rudderClient.setup(WRITE_KEY, {
      dataPlaneUrl: DATA_PLANE_URL,
      controlPlaneUrl: CONTROL_PLANE_URL,
      logLevel: RUDDER_LOG_LEVEL.DEBUG,
    })

    rudderClient.screen('Main Activity', {
      foo: 'bar',
    })
  }

  rudderInitialise()
    .then(() => console.log('SDK is initalised'))
    .catch((err) => console.log('Error in SDK initalisation', err))
```
3. Make any events using 
``` javascript
rudderClient.screen('Main Activity', {
      foo: 'bar',
    })
```

They will not be getting logged on the dashboard

**Expected behavior**
Events are successfully getting fired and getting received on dataPlane

Following is the screenshot of the controlPlane light that we are using to generate workspaceConfig.json for dataPlane
![image](https://github.com/rudderlabs/rudder-sdk-react-native/assets/110530425/a58b431b-32a0-485b-b0f3-aec2900d0029)

**Version of the _React-Native_ SDK**

1. The version of the Rudder React-Native SDK we are using is `1.11.3`

**SDK initialisation snippet**

```javascript
const rudderInitialise = async () => {
    await rudderClient.setup(WRITE_KEY, {
      dataPlaneUrl: DATA_PLANE_URL,
      controlPlaneUrl: CONTROL_PLANE_URL,
      logLevel: RUDDER_LOG_LEVEL.DEBUG,
    })

    rudderClient.screen('Main Activity', {
      foo: 'bar',
    })
  }

  rudderInitialise()
    .then(() => console.log('SDK is initalised'))
    .catch((err) => console.log('Error in SDK initalisation', err))
```

**Framework version of the SDK**
We have tried it with two react-native versions, `0.71.6` and `0.73.2`

**Comment by basit-rayn** [comment]
@keenborder786

**Comment by 1abhishekpandey** [comment]
Hey @basit-rayn,
Thanks for raising this issue. To facilitate a thorough investigation of the issue, could you please adjust the log level to `Verbose` (as shown below)?
```
await rc.setup(WRITE_KEY, {
  dataPlaneUrl: DATA_PLANE_URL,
  controlPlaneUrl: CONTROL_PLANE_URL,
  logLevel: RUDDER_LOG_LEVEL.VERBOSE,
});
```

Following that, please launch your React Native Android application in Android Studio. Open the `logcat` and filter out the logs related to `RudderSDK`. **Please ensure that you share the complete logs**.
<img width="1688" alt="image" src="https://github.com/rudderlabs/rudder-sdk-react-native/assets/64667840/88c71d76-ebc4-4883-9611-0f1a211f971f">

**Comment by 1abhishekpandey** [comment]
Hey @basit-rayn,
Can you please share the log as mentioned in the previous message?

**Comment by nixolas1** [comment]
Hi, we are trying to implement Rudderstack SDK for React Native (With Expo), and are seeing the same issue now. We tested the integration abount a month ago, and saw events in the event stream dashboard.
Checking the logcat logs a events shows up every second or so, which seems excessive when nothing is happening on the device. (the last event, which is prettified. The others only happen once)

https://nixo.no/txt/?a461c4dbe9cc6763#r21Gv+faHXWfzNK+pnfA5devl3M9+43kUjDWIc55ueY=

(external site, due to somewhat sensitive logs)

This is our config:

```json
 const config = {
        dataPlaneUrl: RUDDER_URL,
        trackAppLifecycleEvents: false,
        autoCollectAdvertId: options?.acceptedMarketing,
        recordScreenViews: false,
        withFactories: [firebase],
        logLevel: RUDDER_LOG_LEVEL.VERBOSE,
      }
      await rudderClient.setup(RUDDER_WORKSPACE, config)
```

Contact me at nico@elton.app for any sensitive info. (I'll probably contact you soon enough, we are trying to get rudderstack up and running this week :)

**Comment by 1abhishekpandey** [comment]
Hey @nixolas1, 
From your shared log: https://nixo.no/txt/?a461c4dbe9cc6763#r21Gv+faHXWfzNK+pnfA5devl3M9+43kUjDWIc55ueY=, I could see that events were ingested properly by the SDK. However, since it is not a complete log, I cannot verify some details.

Could you please provide additional information to assist you better?

1. Are you receiving this below response? Please verify it in the Android Studio logcat. I would like to confirm if you are getting a status code of 200. (A status code of 200 essentially indicates that events were successfully sent to the dataPlane URL.)
```
RudderSDK                I  Info: CloudModeManager: cloudModeProcessor: 1
RudderSDK                D  Debug: RudderNetworkManager: sendNetworkRequest: Request URL: https://<DATA_PLANE_URL>.dataplane.rudderstack.com/v1/batch
RudderSDK                D  Debug: RudderNetworkManager: sendNetworkRequest: Gzip is enabled
RudderSDK                I  Info: RudderNetworkManager: sendNetworkRequest: Request to endpoint https://<DATA_PLANE_URL>.dataplane.rudderstack.com/v1/batch was successful with status code 200 and response is OK
RudderSDK                I  Info: CloudModeManager: cloudModeProcessor: ServerResponse: 200
```
2. Are you also utilizing a self-hosted controlPlane and/or dataPlane? If so, could you please attempt to send using our hosted dataPlane URL (create an account over here `https://app.rudderstack.com/`) and inform us whether it is functioning correctly or not?
3. Can you please run your Android app for 30 seconds, generate some events, and share the complete logcat (filtered for RudderSDK, as demonstrated [here](https://github.com/rudderlabs/rudder-sdk-react-native/issues/311#issuecomment-1918679612)). Please ensure to remove any sensitive data such as writeKey, dataPlaneUrl, or other confidential details.

**Comment by basit-rayn** [comment]
Hi @1abhishekpandey!

Here are the logs that I get after setting RUDDER_LOG_LEVEL.verbose.


```log
 LOG  RudderSDK: Debug: Initializing Rudder RN SDK version: 1.11.3
 LOG  RudderSDK: Debug: setup: created config
 LOG  RudderSDK: Debug: setup: setup completed
 LOG  SDK is initalised
```

Also, here is the screenshot when I search for RudderStack in Logcat. It shows nothing.
<img width="1396" alt="Screenshot 2024-02-06 at 12 00 42 PM" src="https://github.com/rudderlabs/rudder-sdk-react-native/assets/110530425/df87b4d5-3a3d-4e36-9f35-96bc389debb6">

**Comment by 1abhishekpandey** [comment]
Hey @basit-rayn,
This shouldn't be the case! The **RudderSDK** log should be generated.
Could you please try opening your React Native Android folder in Android Studio and then, from the Android Studio terminal, run your app? Afterwards, check for the log in the logcat.

Also, is this occurring for iOS as well? If so, could you please try to share the log for that as well?

Please ensure to remove/mask any sensitive data such as writeKey, dataPlaneUrl, or other confidential details from the log.

If you still do not see any logs, please try to provide a minimal reproducible example (share it via GitHub repo) so that I can investigate the setup.

**Comment by basit-rayn** [comment]
@1abhishekpandey I have already opened the project in same way as you are suggesting, like,
` RNProject => android => Open in Android Studio`.

Also, I have not checked it on iOS as our requirement is only for Android currently, and this issue also looks like only on Android as well.


Let me see both situations again and get back to you.

**Comment by nixolas1** [comment]
Seems to work for me again now! No changes on my side, other than restarting the app and dev server (which I had done multiple times yesterday)

**Comment by 1abhishekpandey** [comment]
Glad it has been resolved for you @nixolas1. Please let me know if you encounter any issues in the future.

**Comment by 1abhishekpandey** [comment]
Hey @basit-rayn,
Can you please provide an update?

**Comment by 1abhishekpandey** [comment]
Hey @basit-rayn,
I wanted to inform you that I'm closing this issue as it has been inactive for a significant period of time. While we haven't received any updates or responses regarding this issue, please know that you're always welcome to reopen it if you encounter the problem again or have any additional information to share. Your feedback is valuable to us, and we want to ensure that all issues are addressed promptly.
