### ISSUE TITLE
AnonymousID typescript and safe access error

### ISSUE THREAD

**Issue by connorpmullins** [rudderlabs/rudder-sdk-react-native#355]
Hi there, I'm working in a react native project using version `1.13.1` of the `"@rudderstack/rudder-sdk-react-native"` SDK.

**ISSUE:**
In the below code you can see a red typescript warning
![image](https://github.com/rudderlabs/rudder-sdk-react-native/assets/24562987/e4eed9ae-5bcc-49ee-aae9-847db2abbc54)

The error is that `Type 'unknown' is not assignable to type 'string'`. 

**PROPOSED SOLUTION:**
- Could we type `traits` more strictly than ` Record<string, unknown>`? I'm not sure what other values exist in traits, but manually typing `unknown as string` on my end is both a pain and unsafe.

**EXTRA REQUEST:**
- Could you remove nullability from anonymousID? It might not be possible, but I'm transitioning over from Segment and this is my only pain point so far. We rely on anonymousIDs for unauthenticated users in a number of places and having to handle it possibly being null is actually a little problematic.

**Comment by 1abhishekpandey** [comment]
Hey @connorpmullins,

I understand that you want a better way to fetch the `anonymousId`. 

However, any value you set by calling our [identify](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-react-native-sdk/#identify) API is stored in `traits`. Since users can pass various types (String, Integer, Objects, etc.), we have defined the `traits` type as `Record<string, unknown>`. Therefore, it's not possible for us to change that.

As a temporary workaround, you can convert that value to a String.

A better solution would be for us to introduce a `getAnonymousId` API, which will return the `anonymousId` as a string. This API can be called after the SDK is initialized. I can forward this request to our team, and we will ensure to implement it in the future.

Please let me know if you have any further questions!

**Comment by connorpmullins** [comment]
Thanks @1abhishekpandey ! 

Super helpful - mind updating here if/when `getAnonymousId` gets implemented?

Thank you!
